include ':app'
include ':m01_Screenshots'
include ':m02_Apps'
include ':m03_Interactions'
include ':m05_Activites'
include ':m04_Locations'
include ':m06_Battery'
include ':m07_Power'
include ':m08_Network'
include ':m09_Specs'
include ':c_ModuleManager'
include ':c_DatabaseManager'
include ':c_SharedResources'
